# Automatically generated by configure - do not modify
include ../config-host.mak
TARGET_ARCH=sparc
TARGET_WORDS_BIGENDIAN=yes
CONFIG_SOFTMMU=yes
CONFIG_SOFTFLOAT=yes
CONFIG_SDL=yes
SDL_LIBS=-L/usr/local/mingw32/lib -lmingw32 -lSDLmain -lSDL -mno-cygwin -mwindows
SDL_CFLAGS=-I/usr/local/mingw32/include/SDL -I/usr/include/mingw -mno-cygwin -Dmain=SDL_main
