/* Automatically generated by configure - do not modify */
#define CONFIG_QEMU_SHAREDIR "/usr/local/share/qemu"
#define HOST_I386 1
#define HOST_LONG_BITS 32
#define HAVE_BYTESWAP_H 1
#define CONFIG_GDBSTUB 1
#define CONFIG_SLIRP 1
#define CONFIG_OSS 1
#define CONFIG_ALSA 1
#define QEMU_VERSION "0.9.0"
#define CONFIG_UNAME_RELEASE ""
