/* Automatically generated by configure - do not modify */
#include "../config-host.h"
#define CONFIG_QEMU_PREFIX "/usr/gnemul/qemu-mipsel"
#define TARGET_ARCH "mips"
#define TARGET_MIPS 1
#define CONFIG_SOFTFLOAT 1
#define CONFIG_SOFTMMU 1
#define CONFIG_SDL 1
