# Automatically generated by configure - do not modify
include ../config-host.mak
TARGET_ARCH=arm
CONFIG_SOFTMMU=yes
TARGET_XML_FILES= /home/ddk/download/qemu-0.10.5/gdb-xml/arm-core.xml /home/ddk/download/qemu-0.10.5/gdb-xml/arm-vfp.xml /home/ddk/download/qemu-0.10.5/gdb-xml/arm-vfp3.xml /home/ddk/download/qemu-0.10.5/gdb-xml/arm-neon.xml
CONFIG_SOFTFLOAT=yes
