# Automatically generated by configure - do not modify
include ../config-host.mak
TARGET_ARCH=ppc
TARGET_WORDS_BIGENDIAN=yes
CONFIG_SOFTMMU=yes
TARGET_XML_FILES= /home/ddk/download/qemu-0.10.5/gdb-xml/power-core.xml /home/ddk/download/qemu-0.10.5/gdb-xml/power-fpu.xml /home/ddk/download/qemu-0.10.5/gdb-xml/power-altivec.xml /home/ddk/download/qemu-0.10.5/gdb-xml/power-spe.xml
CONFIG_SOFTFLOAT=yes
